apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.netflix.deploymentName }}
spec:
  replicas: {{ .Values.netflix.replicas }}
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix-container
        image: {{ .Values.netflix.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000

